[workspace]
members = ["macros", "utils", "tools/sl", "tools/timer", "tools/install"]

[package]
name = "build-your-own"
version = "0.1.0"
edition = "2021"

[dependencies]
build-your-own-macros = { path = "macros" }
build-your-own-utils = { path = "utils" }
sl = { path = "tools/sl" }
timer = { path = "tools/timer" }
install = { path = "tools/install" }

[dev-dependencies]
build-your-own-macros-tests = { path = "macros_tests" }
