[workspace]
members = ["macros", "utils"]

[package]
name = "build-your-own"
version = "0.1.0"
edition = "2021"

[dependencies]
build-your-own-macros = { path = "macros" }
build-your-own-utils = { path = "utils" }
