[package]
name = "build-your-own-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
build-your-own-shared = { path = "../shared" }
quote = "1.0.36"
proc-macro2 = "1.0.86"
