[package]
name = "pmi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
build-your-own-utils = { path = "../../utils" }
build-your-own-macros = { path = "../../macros" }

[features]
default = ["apt", "brew", "cargo", "npm", "executable_file", "snap", "install_sh"]
general = ["brew", "cargo", "npm", "executable_file", "snap", "install_sh"]
ubuntu = ["general", "apt"]
fedora = ["general"]
apt = []
brew = []
cargo = []
npm = []
executable_file = []
snap = []
install_sh = []
